global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'retention-api'
    static_configs:
      - targets: ['prometheus-retention-api:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'blackbox_mama_mta'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://mama.mta.ac.il/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # שם השירות ב-docker-compose

# Example: Add your application metrics here
# - job_name: 'my-app'
#   static_configs:
#     - targets: ['my-app:8080']